# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myLogNorm <- function(data, scale_factor, display_progress = TRUE) {
    .Call(`_avinash_scRNA_myLogNorm`, data, scale_factor, display_progress)
}

